services:
  test-indexer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_CONNECTION_STR: postgresql://postgres:password@postgres:5432/pipes
    command: ["sh", "-lc", "pnpm db:generate && pnpm db:migrate && node dist/index.js"]
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    profiles: ["with-pipeline"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pipes
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

