import { program } from 'commander'

import pkg from '../package.json' with { type: 'json' }
import { CONFIG_SCHEMA_URL } from './commands/init/config/params.js'
import { InitHandler } from './commands/init/init.handler.js'
import { InitPrompt } from './commands/init/init.prompt.js'
import { ConfigService } from './services/config.service.js'
import { withErrorHandling } from './utils/error-handling.js'
import { getInputType } from './utils/string.js'

program.name('pipes').description('Subsquid Pipes CLI').version(pkg.version)

program
  .command('init')
  .description('Initialize a new pipe project')
  .option(
    '--config <json | file>',
    `JSON configuration string to skip prompts, or a path to a config file. JSON schema: ${CONFIG_SCHEMA_URL} (or run \`pipes init --schema\`).`,
  )
  .option('--config-id <id>', 'Use the config ID generated by the Pipes Starter UI')
  .option('--schema', 'Print the JSON schema for `--config` and exit')
  .action(
    withErrorHandling(async (options) => {
      if (options.config) {
        const { type, content } = getInputType(options.config)
        let handler
        switch (type) {
          case 'json':
            handler = await InitHandler.fromJson(content)
            break
          case 'file':
            handler = await InitHandler.fromFile(content)
            break
        }

        await handler.handle()
      } else if (options.configId) {
        const configService = new ConfigService()
        const configJson = await configService.getConfigJsonByHash(options.configId)
        const handler = await InitHandler.fromJson(configJson)
        await handler.handle()
      } else if (options.schema) {
        InitHandler.jsonSchema()
      } else {
        const initConfig = new InitPrompt()
        await initConfig.run()
      }
    }),
  )

program.parse()
