import { NetworkType } from '~/types/network.js'

export const evmNetworks = [
  {
    name: '0g Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '16600',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: '0g-testnet',
    details: '/en/data/evm/0g-testnet/overview',
  },
  {
    name: 'Abstract',
    type: 'mainnet',
    tooltip: null,
    chainId: '2741',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'abstract-mainnet',
    details: '/en/data/evm/abstract-mainnet/overview',
  },
  {
    name: 'Abstract Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '11124',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'abstract-testnet',
    details: '/en/data/evm/abstract-testnet/overview',
  },
  {
    name: 'Agung',
    type: 'testnet',
    tooltip: null,
    chainId: '9990',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'agung-evm',
    details: '/en/data/evm/agung-evm/overview',
  },
  {
    name: 'Aleph Zero EVM',
    type: 'mainnet',
    tooltip: null,
    chainId: '41455',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'aleph-zero-evm-mainnet',
    details: '/en/data/evm/aleph-zero-evm-mainnet/overview',
  },
  {
    name: 'Arbitrum Blueberry',
    type: 'testnet',
    tooltip: null,
    chainId: '88153591557',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'gelato-arbitrum-blueberry',
    details: '/en/data/evm/gelato-arbitrum-blueberry/overview',
  },
  {
    name: 'Arbitrum Nova',
    type: 'mainnet',
    tooltip: null,
    chainId: '42170',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: false,
    slug: 'arbitrum-nova',
    details: '/en/data/evm/arbitrum-nova/overview',
  },
  {
    name: 'Arbitrum One',
    type: 'mainnet',
    tooltip: null,
    chainId: '42161',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: false,
    slug: 'arbitrum-one',
    details: '/en/data/evm/arbitrum-one/overview',
  },
  {
    name: 'Arbitrum Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '421614',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: false,
    slug: 'arbitrum-sepolia',
    details: '/en/data/evm/arbitrum-sepolia/overview',
  },
  {
    name: 'Arthera',
    type: 'mainnet',
    tooltip: null,
    chainId: '10242',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'arthera-mainnet',
    details: '/en/data/evm/arthera-mainnet/overview',
  },
  {
    name: 'Astar',
    type: 'mainnet',
    tooltip: null,
    chainId: '592',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'astar-mainnet',
    details: '/en/data/evm/astar-mainnet/overview',
  },
  {
    name: 'Astar zkEVM',
    type: 'mainnet',
    tooltip: null,
    chainId: '3776',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'astar-zkevm-mainnet',
    details: '/en/data/evm/astar-zkevm-mainnet/overview',
  },
  {
    name: 'Astar zKyoto',
    type: 'testnet',
    tooltip: null,
    chainId: '6038361',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'astar-zkyoto',
    details: '/en/data/evm/astar-zkyoto/overview',
  },
  {
    name: 'Avalanche',
    type: 'mainnet',
    tooltip: null,
    chainId: '43114',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: true,
    slug: 'avalanche-mainnet',
    details: '/en/data/evm/avalanche-mainnet/overview',
  },
  {
    name: 'Avalanche Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '43113',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'avalanche-testnet',
    details: '/en/data/evm/avalanche-testnet/overview',
  },
  {
    name: 'B3',
    type: 'mainnet',
    tooltip: null,
    chainId: '8333',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'b3-mainnet',
    details: '/en/data/evm/b3-mainnet/overview',
  },
  {
    name: 'B3 Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '1993',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'b3-sepolia',
    details: '/en/data/evm/b3-sepolia/overview',
  },
  {
    name: 'Base',
    type: 'mainnet',
    tooltip: null,
    chainId: '8453',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: true,
    slug: 'base-mainnet',
    details: '/en/data/evm/base-mainnet/overview',
  },
  {
    name: 'Base Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '84532',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'base-sepolia',
    details: '/en/data/evm/base-sepolia/overview',
  },
  {
    name: 'Beam',
    type: 'mainnet',
    tooltip: null,
    chainId: '4337',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'beam-mainnet',
    details: '/en/data/evm/beam-mainnet/overview',
  },
  {
    name: 'Berachain bArtio',
    type: 'testnet',
    tooltip: null,
    chainId: '80084',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'berachain-bartio',
    details: '/en/data/evm/berachain-bartio/overview',
  },
  {
    name: 'Berachain',
    type: 'mainnet',
    tooltip: null,
    chainId: '80094',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'berachain-mainnet',
    details: '/en/data/evm/berachain-mainnet/overview',
  },
  {
    name: 'BSC',
    type: 'mainnet',
    tooltip: null,
    chainId: '56',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: true,
    slug: 'binance-mainnet',
    details: '/en/data/evm/binance-mainnet/overview',
  },
  {
    name: 'BSC Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '97',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'binance-testnet',
    details: '/en/data/evm/binance-testnet/overview',
  },
  {
    name: 'Bitfinity',
    type: 'mainnet',
    tooltip: null,
    chainId: '355110',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'bitfinity-mainnet',
    details: '/en/data/evm/bitfinity-mainnet/overview',
  },
  {
    name: 'Bitfinity Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '355113',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'bitfinity-testnet',
    details: '/en/data/evm/bitfinity-testnet/overview',
  },
  {
    name: 'Bitgert',
    type: 'mainnet',
    tooltip: null,
    chainId: '32520',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: false,
    slug: 'bitgert-mainnet',
    details: '/en/data/evm/bitgert-mainnet/overview',
  },
  {
    name: 'Bitgert Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '64668',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'bitgert-testnet',
    details: '/en/data/evm/bitgert-testnet/overview',
  },
  {
    name: 'Bittensor',
    type: 'mainnet',
    tooltip: null,
    chainId: '964',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'bittensor-mainnet-evm',
    details: '/en/data/evm/bittensor-mainnet-evm/overview',
  },
  {
    name: 'Bittensor Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '945',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'bittensor-testnet-evm',
    details: '/en/data/evm/bittensor-testnet-evm/overview',
  },
  {
    name: 'Blast L2',
    type: 'mainnet',
    tooltip: null,
    chainId: '81457',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'blast-l2-mainnet',
    details: '/en/data/evm/blast-l2-mainnet/overview',
  },
  {
    name: 'Blast Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '168587773',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'blast-sepolia',
    details: '/en/data/evm/blast-sepolia/overview',
  },
  {
    name: 'BOB',
    type: 'mainnet',
    tooltip: null,
    chainId: '60808',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'bob-mainnet',
    details: '/en/data/evm/bob-mainnet/overview',
  },
  {
    name: 'BOB Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '808813',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'bob-sepolia',
    details: '/en/data/evm/bob-sepolia/overview',
  },
  {
    name: 'Botanix',
    type: 'mainnet',
    tooltip: null,
    chainId: '3637',
    portal: false,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'botanix-mainnet',
    details: '/en/data/evm/botanix-mainnet/overview',
  },
  {
    name: 'Botanix Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '3636',
    portal: false,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'botanix-testnet',
    details: '/en/data/evm/botanix-testnet/overview',
  },
  {
    name: 'Camp Network Testnet v2',
    type: 'testnet',
    tooltip: null,
    chainId: '325000',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'camp-network-testnet-v2',
    details: '/en/data/evm/camp-network-testnet-v2/overview',
  },
  {
    name: 'Canto',
    type: 'mainnet',
    tooltip: null,
    chainId: '7700',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'canto',
    details: '/en/data/evm/canto/overview',
  },
  {
    name: 'Canto Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '7701',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'canto-testnet',
    details: '/en/data/evm/canto-testnet/overview',
  },
  {
    name: 'Celo',
    type: 'mainnet',
    tooltip: null,
    chainId: '42220',
    portal: true,
    realtime: true,
    traces: false,
    stateDiffs: false,
    slug: 'celo-mainnet',
    details: '/en/data/evm/celo-mainnet/overview',
  },
  {
    name: 'Celo Testnet (Alfajores)',
    type: 'testnet',
    tooltip: null,
    chainId: '44787',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'celo-alfajores-testnet',
    details: '/en/data/evm/celo-alfajores-testnet/overview',
  },
  {
    name: 'Core',
    type: 'mainnet',
    tooltip: null,
    chainId: '1116',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'core-mainnet',
    details: '/en/data/evm/core-mainnet/overview',
  },
  {
    name: 'CrossFi',
    type: 'mainnet',
    tooltip: null,
    chainId: '4158',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'crossfi-mainnet',
    details: '/en/data/evm/crossfi-mainnet/overview',
  },
  {
    name: 'CrossFi Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '4157',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'crossfi-testnet',
    details: '/en/data/evm/crossfi-testnet/overview',
  },
  {
    name: 'Cyber',
    type: 'mainnet',
    tooltip: null,
    chainId: '7560',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'cyber-mainnet',
    details: '/en/data/evm/cyber-mainnet/overview',
  },
  {
    name: 'Cyberconnect L2 Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '111557560',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'cyberconnect-l2-testnet',
    details: '/en/data/evm/cyberconnect-l2-testnet/overview',
  },
  {
    name: 'Dancelight',
    type: 'testnet',
    tooltip: null,
    chainId: '5678',
    portal: false,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'dancelight-testnet',
    details: '/en/data/evm/dancelight-testnet/overview',
  },
  {
    name: 'Degen Chain',
    type: 'mainnet',
    tooltip: null,
    chainId: '666666666',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'degen-chain',
    details: '/en/data/evm/degen-chain/overview',
  },
  {
    name: 'DFK Chain',
    type: 'mainnet',
    tooltip: null,
    chainId: '53935',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'dfk-chain',
    details: '/en/data/evm/dfk-chain/overview',
  },
  {
    name: 'Dogechain',
    type: 'mainnet',
    tooltip: null,
    chainId: '2000',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'dogechain-mainnet',
    details: '/en/data/evm/dogechain-mainnet/overview',
  },
  {
    name: 'Dogechain Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '568',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'dogechain-testnet',
    details: '/en/data/evm/dogechain-testnet/overview',
  },
  {
    name: 'Ethereum',
    type: 'mainnet',
    tooltip: null,
    chainId: '1',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: true,
    slug: 'ethereum-mainnet',
    details: '/en/data/evm/ethereum-mainnet/overview',
  },
  {
    name: 'Ethereum Holesky',
    type: 'testnet',
    tooltip: null,
    chainId: '17000',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'ethereum-holesky',
    details: '/en/data/evm/ethereum-holesky/overview',
  },
  {
    name: 'Ethereum Hoodi',
    type: 'testnet',
    tooltip: null,
    chainId: '560048',
    portal: false,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'ethereum-hoodi',
    details: '/en/data/evm/ethereum-hoodi/overview',
  },
  {
    name: 'Ethereum Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '11155111',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: true,
    slug: 'ethereum-sepolia',
    details: '/en/data/evm/ethereum-sepolia/overview',
  },
  {
    name: 'Etherlink',
    type: 'mainnet',
    tooltip: null,
    chainId: '42793',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'etherlink-mainnet',
    details: '/en/data/evm/etherlink-mainnet/overview',
  },
  {
    name: 'Etherlink Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '128123',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'etherlink-testnet',
    details: '/en/data/evm/etherlink-testnet/overview',
  },
  {
    name: 'Exosama',
    type: 'mainnet',
    tooltip: null,
    chainId: '2109',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'exosama',
    details: '/en/data/evm/exosama/overview',
  },
  {
    name: 'Fantom',
    type: 'mainnet',
    tooltip: null,
    chainId: '250',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'fantom-mainnet',
    details: '/en/data/evm/fantom-mainnet/overview',
  },
  {
    name: 'Fantom Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '4002',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'fantom-testnet',
    details: '/en/data/evm/fantom-testnet/overview',
  },
  {
    name: 'Flare',
    type: 'mainnet',
    tooltip: null,
    chainId: '14',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'flare-mainnet',
    details: '/en/data/evm/flare-mainnet/overview',
  },
  {
    name: 'Gelato Opcelestia Raspberry',
    type: 'mainnet',
    tooltip: null,
    chainId: '123420111',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'gelato-opcelestia-raspberry',
    details: '/en/data/evm/gelato-opcelestia-raspberry/overview',
  },
  {
    name: 'Gnosis',
    type: 'mainnet',
    tooltip: null,
    chainId: '100',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'gnosis-mainnet',
    details: '/en/data/evm/gnosis-mainnet/overview',
  },
  {
    name: 'Gravity',
    type: 'mainnet',
    tooltip: null,
    chainId: '1625',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'galxe-gravity',
    details: '/en/data/evm/galxe-gravity/overview',
  },
  {
    name: 'Hedera',
    type: 'mainnet',
    tooltip: null,
    chainId: '295',
    portal: false,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'hedera-mainnet',
    details: '/en/data/evm/hedera-mainnet/overview',
  },
  {
    name: 'Hemi',
    type: 'mainnet',
    tooltip: null,
    chainId: '43111',
    portal: false,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'hemi-mainnet',
    details: '/en/data/evm/hemi-mainnet/overview',
  },
  {
    name: 'Hemi Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '743111',
    portal: false,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'hemi-testnet',
    details: '/en/data/evm/hemi-testnet/overview',
  },
  {
    name: 'HyperEVM',
    type: 'mainnet',
    tooltip: null,
    chainId: '999',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: true,
    slug: 'hyperliquid-mainnet',
    details: '/en/data/evm/hyperevm-mainnet/overview',
  },
  {
    name: 'HyperEVM Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '998',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'hyperliquid-testnet',
    details: '/en/data/evm/hyperevm-testnet/overview',
  },
  {
    name: 'Immutable zkEVM',
    type: 'mainnet',
    tooltip: null,
    chainId: '13371',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'immutable-zkevm-mainnet',
    details: '/en/data/evm/immutable-zkevm-mainnet/overview',
  },
  {
    name: 'Immutable zkEVM Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '13473',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'immutable-zkevm-testnet',
    details: '/en/data/evm/immutable-zkevm-testnet/overview',
  },
  {
    name: 'Ink',
    type: 'mainnet',
    tooltip: null,
    chainId: '57073',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'ink-mainnet',
    details: '/en/data/evm/ink-mainnet/overview',
  },
  {
    name: 'Ink Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '763373',
    portal: false,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'ink-sepolia',
    details: '/en/data/evm/ink-sepolia/overview',
  },
  {
    name: 'Kyoto Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '1998',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'kyoto-testnet',
    details: '/en/data/evm/kyoto-testnet/overview',
  },
  {
    name: 'Linea',
    type: 'mainnet',
    tooltip: null,
    chainId: '59144',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'linea-mainnet',
    details: '/en/data/evm/linea-mainnet/overview',
  },
  {
    name: 'Lukso',
    type: 'mainnet',
    tooltip: null,
    chainId: '42',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'lukso-mainnet',
    details: '/en/data/evm/lukso-mainnet/overview',
  },
  {
    name: 'Manta Pacific',
    type: 'mainnet',
    tooltip: null,
    chainId: '169',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'manta-pacific',
    details: '/en/data/evm/manta-pacific/overview',
  },
  {
    name: 'Manta Pacific Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '3441006',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'manta-pacific-sepolia',
    details: '/en/data/evm/manta-pacific-sepolia/overview',
  },
  {
    name: 'Mantle',
    type: 'mainnet',
    tooltip: null,
    chainId: '5000',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'mantle-mainnet',
    details: '/en/data/evm/mantle-mainnet/overview',
  },
  {
    name: 'Mantle Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '5003',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'mantle-sepolia',
    details: '/en/data/evm/mantle-sepolia/overview',
  },
  {
    name: 'Mega Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '6342',
    portal: false,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'mega-testnet',
    details: '/en/data/evm/mega-testnet/overview',
  },
  {
    name: 'MemeCore',
    type: 'mainnet',
    tooltip: null,
    chainId: '4352',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'memecore-mainnet',
    details: '/en/data/evm/memecore-mainnet/overview',
  },
  {
    name: 'MemeCore Testnet (Formicarium)',
    type: 'testnet',
    tooltip: null,
    chainId: '43521',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'formicarium-testnet',
    details: '/en/data/evm/formicarium-testnet/overview',
  },
  {
    name: 'Merlin',
    type: 'mainnet',
    tooltip: null,
    chainId: '4200',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'merlin-mainnet',
    details: '/en/data/evm/merlin-mainnet/overview',
  },
  {
    name: 'Merlin Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '686868',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'merlin-testnet',
    details: '/en/data/evm/merlin-testnet/overview',
  },
  {
    name: 'Metis',
    type: 'mainnet',
    tooltip: null,
    chainId: '1088',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'metis-mainnet',
    details: '/en/data/evm/metis-mainnet/overview',
  },
  {
    name: 'Mode',
    type: 'mainnet',
    tooltip: null,
    chainId: '34443',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'mode-mainnet',
    details: '/en/data/evm/mode-mainnet/overview',
  },
  {
    name: 'Monad',
    type: 'mainnet',
    tooltip: null,
    chainId: '143',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'monad-mainnet',
    details: '/en/data/evm/monad-mainnet/overview',
  },
  {
    name: 'Monad Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '10143',
    portal: true,
    realtime: true,
    traces: false,
    stateDiffs: false,
    slug: 'monad-testnet',
    details: '/en/data/evm/monad-testnet/overview',
  },
  {
    name: 'Moonbase Alpha',
    type: 'testnet',
    tooltip: null,
    chainId: '1287',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'moonbase-testnet',
    details: '/en/data/evm/moonbase-testnet/overview',
  },
  {
    name: 'Moonbeam',
    type: 'mainnet',
    tooltip: null,
    chainId: '1284',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'moonbeam-mainnet',
    details: '/en/data/evm/moonbeam-mainnet/overview',
  },
  {
    name: 'Moonriver',
    type: 'mainnet',
    tooltip: null,
    chainId: '1285',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'moonriver-mainnet',
    details: '/en/data/evm/moonriver-mainnet/overview',
  },
  {
    name: 'Moonsama',
    type: 'mainnet',
    tooltip: null,
    chainId: '2199',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'moonsama',
    details: '/en/data/evm/moonsama/overview',
  },
  {
    name: 'Naka Chain',
    type: 'mainnet',
    tooltip: null,
    chainId: '42225',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'nakachain',
    details: '/en/data/evm/nakachain/overview',
  },
  {
    name: 'Neon EVM',
    type: 'mainnet',
    tooltip: null,
    chainId: '245022934',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'neon-mainnet',
    details: '/en/data/evm/neon-mainnet/overview',
  },
  {
    name: 'Neon EVM Devnet',
    type: 'devnet',
    tooltip: null,
    chainId: '245022926',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'neon-devnet',
    details: '/en/data/evm/neon-devnet/overview',
  },
  {
    name: 'Neox Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '12227331',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'neox-testnet',
    details: '/en/data/evm/neox-testnet/overview',
  },
  {
    name: 'opBNB',
    type: 'mainnet',
    tooltip: null,
    chainId: '204',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'opbnb-mainnet',
    details: '/en/data/evm/opbnb-mainnet/overview',
  },
  {
    name: 'opBNB Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '5611',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'opbnb-testnet',
    details: '/en/data/evm/opbnb-testnet/overview',
  },
  {
    name: 'Optimism',
    type: 'mainnet',
    tooltip: null,
    chainId: '10',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'optimism-mainnet',
    details: '/en/data/evm/optimism-mainnet/overview',
  },
  {
    name: 'Optimism Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '11155420',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'optimism-sepolia',
    details: '/en/data/evm/optimism-sepolia/overview',
  },
  {
    name: 'Ozean Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '7849306',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'ozean-testnet',
    details: '/en/data/evm/ozean-testnet/overview',
  },
  {
    name: 'Peaq',
    type: 'mainnet',
    tooltip: null,
    chainId: '3338',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'peaq-mainnet',
    details: '/en/data/evm/peaq-mainnet/overview',
  },
  {
    name: 'Plasma',
    type: 'mainnet',
    tooltip: null,
    chainId: '9745',
    portal: true,
    realtime: true,
    traces: false,
    stateDiffs: false,
    slug: 'plasma-mainnet',
    details: '/en/data/evm/plasma-mainnet/overview',
  },
  {
    name: 'Plasma Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '9746',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'plasma-testnet',
    details: '/en/data/evm/plasma-testnet/overview',
  },
  {
    name: 'Plume Devnet',
    type: 'devnet',
    tooltip: null,
    chainId: '98864',
    portal: false,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'plume-devnet',
    details: '/en/data/evm/plume-devnet/overview',
  },
  {
    name: 'Plume',
    type: 'mainnet',
    tooltip: null,
    chainId: '98866',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'plume-mainnet',
    details: '/en/data/evm/plume-mainnet/overview',
  },
  {
    name: 'Plume (Legacy)',
    type: 'mainnet',
    tooltip: null,
    chainId: '98865',
    portal: false,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'plume-legacy',
    details: '/en/data/evm/plume-legacy/overview',
  },
  {
    name: 'Plume Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '98867',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'plume-testnet',
    details: '/en/data/evm/plume-testnet/overview',
  },
  {
    name: 'Polygon',
    type: 'mainnet',
    tooltip: null,
    chainId: '137',
    portal: true,
    realtime: true,
    traces: false,
    stateDiffs: true,
    slug: 'polygon-mainnet',
    details: '/en/data/evm/polygon-mainnet/overview',
  },
  {
    name: 'Polygon Amoy Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '80002',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'polygon-amoy-testnet',
    details: '/en/data/evm/polygon-amoy-testnet/overview',
  },
  {
    name: 'Polygon zkEVM',
    type: 'mainnet',
    tooltip: null,
    chainId: '1101',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'polygon-zkevm-mainnet',
    details: '/en/data/evm/polygon-zkevm-mainnet/overview',
  },
  {
    name: 'Polygon zkEVM Cardona Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '2442',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'polygon-zkevm-cardona-testnet',
    details: '/en/data/evm/polygon-zkevm-cardona-testnet/overview',
  },
  {
    name: 'Poseidon Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '31911',
    portal: false,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'poseidon-testnet',
    details: '/en/data/evm/poseidon-testnet/overview',
  },
  {
    name: 'Prom',
    type: 'mainnet',
    tooltip: null,
    chainId: '227',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'prom-mainnet',
    details: '/en/data/evm/prom-mainnet/overview',
  },
  {
    name: "Puppynet (Shibarium's Testnet)",
    type: 'testnet',
    tooltip: null,
    chainId: '157',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'puppynet',
    details: '/en/data/evm/puppynet/overview',
  },
  {
    name: 'Scroll',
    type: 'mainnet',
    tooltip: null,
    chainId: '534352',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'scroll-mainnet',
    details: '/en/data/evm/scroll-mainnet/overview',
  },
  {
    name: 'Scroll Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '534351',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'scroll-sepolia',
    details: '/en/data/evm/scroll-sepolia/overview',
  },
  {
    name: 'Shibarium',
    type: 'mainnet',
    tooltip: null,
    chainId: '109',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'shibarium',
    details: '/en/data/evm/shibarium/overview',
  },
  {
    name: 'Shibuya',
    type: 'testnet',
    tooltip: null,
    chainId: '81',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'shibuya-testnet',
    details: '/en/data/evm/shibuya-testnet/overview',
  },
  {
    name: 'Shiden',
    type: 'mainnet',
    tooltip: null,
    chainId: '336',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'shiden-mainnet',
    details: '/en/data/evm/shiden-mainnet/overview',
  },
  {
    name: 'Skale Nebula',
    type: 'mainnet',
    tooltip: null,
    chainId: '1482601649',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'skale-nebula',
    details: '/en/data/evm/skale-nebula/overview',
  },
  {
    name: 'Soneium',
    type: 'mainnet',
    tooltip: null,
    chainId: '1868',
    portal: true,
    realtime: true,
    traces: false,
    stateDiffs: false,
    slug: 'soneium-mainnet',
    details: '/en/data/evm/soneium-mainnet/overview',
  },
  {
    name: 'Soneium Minato Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '1946',
    portal: false,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'soneium-minato-testnet',
    details: '/en/data/evm/soneium-minato-testnet/overview',
  },
  {
    name: 'Sonic',
    type: 'mainnet',
    tooltip: null,
    chainId: '146',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'sonic-mainnet',
    details: '/en/data/evm/sonic-mainnet/overview',
  },
  {
    name: 'Sonic Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '14601',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'sonic-testnet',
    details: '/en/data/evm/sonic-testnet/overview',
  },
  {
    name: 'StratoVM Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '93747',
    portal: true,
    realtime: false,
    traces: true,
    stateDiffs: true,
    slug: 'stratovm-sepolia',
    details: '/en/data/evm/stratovm-sepolia/overview',
  },
  {
    name: 'Superseed',
    type: 'mainnet',
    tooltip: null,
    chainId: '5330',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'superseed-mainnet',
    details: '/en/data/evm/superseed-mainnet/overview',
  },
  {
    name: 'Superseed Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '53302',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'superseed-sepolia',
    details: '/en/data/evm/superseed-sepolia/overview',
  },
  {
    name: 'Taiko',
    type: 'mainnet',
    tooltip: null,
    chainId: '167000',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'taiko-mainnet',
    details: '/en/data/evm/taiko-mainnet/overview',
  },
  {
    name: 'Tanssi',
    type: 'mainnet',
    tooltip: null,
    chainId: '5678',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'tanssi',
    details: '/en/data/evm/tanssi/overview',
  },
  {
    name: 'Unichain',
    type: 'mainnet',
    tooltip: null,
    chainId: '130',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: true,
    slug: 'unichain-mainnet',
    details: '/en/data/evm/unichain-mainnet/overview',
  },
  {
    name: 'Unichain Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '1301',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'unichain-sepolia',
    details: '/en/data/evm/unichain-sepolia/overview',
  },
  {
    name: 'X Layer',
    type: 'mainnet',
    tooltip: null,
    chainId: '196',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'xlayer-mainnet',
    details: '/en/data/evm/xlayer-mainnet/overview',
  },
  {
    name: 'X Layer Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '195',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'xlayer-testnet',
    details: '/en/data/evm/xlayer-testnet/overview',
  },
  {
    name: 'X1 Testnet',
    type: 'testnet',
    tooltip: null,
    chainId: '204005',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'x1-testnet',
    details: '/en/data/evm/x1-testnet/overview',
  },
  {
    name: 'zkLink Nova',
    type: 'mainnet',
    tooltip: null,
    chainId: '810180',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'zklink-nova-mainnet',
    details: '/en/data/evm/zklink-nova-mainnet/overview',
  },
  {
    name: 'zkSync',
    type: 'mainnet',
    tooltip: null,
    chainId: '324',
    portal: true,
    realtime: true,
    traces: false,
    stateDiffs: true,
    slug: 'zksync-mainnet',
    details: '/en/data/evm/zksync-mainnet/overview',
  },
  {
    name: 'zkSync Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '300',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: true,
    slug: 'zksync-sepolia',
    details: '/en/data/evm/zksync-sepolia/overview',
  },
  {
    name: 'Zora',
    type: 'mainnet',
    tooltip: null,
    chainId: '7777777',
    portal: true,
    realtime: true,
    traces: true,
    stateDiffs: true,
    slug: 'zora-mainnet',
    details: '/en/data/evm/zora-mainnet/overview',
  },
  {
    name: 'Zora Sepolia',
    type: 'testnet',
    tooltip: null,
    chainId: '999999999',
    portal: true,
    realtime: false,
    traces: false,
    stateDiffs: false,
    slug: 'zora-sepolia',
    details: '/en/data/evm/zora-sepolia/overview',
  },
] as const

export const solanaNetworks = [
  {
    name: 'Solana',
    type: 'mainnet',
    tooltip: null,
    portal: true,
    realtime: true,
    slug: 'solana-mainnet',
    details: '/en/data/solana/solana-mainnet/overview',
  },
  {
    name: 'Solana Devnet',
    type: 'devnet',
    tooltip: null,
    portal: true,
    realtime: true,
    slug: 'solana-devnet',
    details: '/en/data/solana/solana-devnet/overview',
  },
  {
    name: 'Eclipse',
    type: 'mainnet',
    tooltip: null,
    portal: true,
    realtime: false,
    slug: 'eclipse-mainnet',
    details: '/en/data/solana/eclipse-mainnet/overview',
  },
  {
    name: 'Eclipse Testnet',
    type: 'testnet',
    tooltip: null,
    portal: true,
    realtime: false,
    slug: 'eclipse-testnet',
    details: '/en/data/solana/eclipse-testnet/overview',
  },
  {
    name: 'SOON',
    type: 'mainnet',
    tooltip: null,
    portal: true,
    realtime: false,
    slug: 'soon-mainnet',
    details: '/en/data/solana/soon-mainnet/overview',
  },
  {
    name: 'SOON Testnet',
    type: 'testnet',
    tooltip: null,
    portal: true,
    realtime: false,
    slug: 'soon-testnet',
    details: '/en/data/solana/soon-testnet/overview',
  },
  {
    name: 'SOON Devnet',
    type: 'devnet',
    tooltip: null,
    portal: true,
    realtime: false,
    slug: 'soon-devnet',
    details: '/en/data/solana/soon-devnet/overview',
  },
  {
    name: 'svmBNB',
    type: 'mainnet',
    tooltip: null,
    portal: true,
    realtime: false,
    slug: 'svm-bnb-mainnet',
    details: '/en/data/solana/svm-bnb-mainnet/overview',
  },
  {
    name: 'svmBNB Testnet',
    type: 'testnet',
    tooltip: null,
    portal: true,
    realtime: false,
    slug: 'svm-bnb-testnet',
    details: '/en/data/solana/svm-bnb-testnet/overview',
  },
] as const

export const networks: Record<NetworkType, typeof evmNetworks | typeof solanaNetworks> = {
  evm: evmNetworks,
  svm: solanaNetworks,
}

export function getEvmChainId(slug: string): string | undefined {
  return evmNetworks.find((n) => n.slug === slug)?.chainId
}
