import { program } from 'commander'
import { InitHandler } from './commands/init/init.handler.js'
import { InitPrompt } from './commands/init/init.prompt.js'
import { ConfigService } from './services/config.service.js'
import { withErrorHandling } from './utils/error-handling.js'
import { getInputType } from './utils/string.js'

program.name('pipes').description('Subsquid Pipes CLI').version('0.1.0')

program
  .command('init')
  .description('Initialize a new pipe project')
  .option('--config <json>', 'JSON configuration string to skip prompts')
  .option('--config-id <id>', 'Use the config ID generated by the Pipes Starter UI')
  .option('--schema', 'Outputs the config used schema used for `--config` option')
  .action(withErrorHandling(async (options) => {
      if (options.config) {
        const { type, content } = getInputType(options.config)
        switch (type) {
          case 'json':
            await InitHandler.fromJson(content).handle()
            break
          case 'file':
            await InitHandler.fromFile(content).handle()
            break
        }
      } else if (options.configId) {
        const configService = new ConfigService()
        const config = await configService.getConfigJsonByHash(options.configId)
        await InitHandler.fromJson(config).handle()
      } else if (options.schema) {
        InitHandler.jsonSchema()
      } else {
        const initConfig = new InitPrompt()
      await initConfig.run()
    }
  }))

program.parse()
