import { program } from 'commander'

import { DeployHandler } from './commands/deploy/deploy.handler.js'
import { DeployOptionsSchema } from './commands/deploy/deploy.schema.js'
import { InitHandler } from './commands/init/init.handler.js'
import { InitPrompt } from './commands/init/init.prompt.js'
import { ConfigService } from './services/config.service.js'
import { withErrorHandling } from './utils/error-handling.js'

program.name('pipes').description('Subsquid Pipes CLI').version('111.1.0')

program
  .command('init')
  .description('Initialize a new pipe project')
  .option('--config <json>', 'JSON configuration string to skip prompts')
  .option('--config-id <id>', 'Use the config ID generated by the Pipes Starter UI')
  .action(
    withErrorHandling(async (options) => {
      if (options.config) {
        await InitHandler.fromJson(options.config).handle()
      } else if (options.configId) {
        const configService = new ConfigService()
        const config = await configService.getConfigJsonByHash(options.configId)
        await InitHandler.fromJson(config).handle()
      } else {
        const initConfig = new InitPrompt()
        await initConfig.run()
      }
    }),
  )

program
  .command('deploy')
  .description('Deploy a pipe project to one of the supported providers')
  .option('--provider <provider>', 'Provider to deploy to', 'railway')
  .action(
    withErrorHandling(async (options) => {
      const deployOptions = DeployOptionsSchema.parse(options)
      const deployHandler = new DeployHandler(deployOptions)
      await deployHandler.handle()
    }),
  )

program.parse()
