import { program } from 'commander'
import { InitHandler } from './commands/init/init.handler.js'
import { InitPrompt } from './commands/init/init.prompt.js'
import { ConfigService } from './services/config.service.js'

function formatError(error: unknown): string {
  if (error instanceof Error) {
    return error.message
  }
  if (typeof error === 'string') {
    return error
  }
  return 'An unexpected error occurred'
}

program.name('pipes').description('Subsquid Pipes CLI').version('0.1.0')

program
  .command('init')
  .description('Initialize a new pipe project')
  .option('--config <json>', 'JSON configuration string to skip prompts')
  .option('--config-id <id>', 'Use the config ID generated by the Pipes Starter UI')
  .action(async (options) => {
    try {
      if (options.config) {
        await InitHandler.fromJson(options.config).handle()
      } else if (options.configId) {
        const configService = new ConfigService()
        const config = await configService.getConfigJsonByHash(options.configId)
        await InitHandler.fromJson(config).handle()
      } else {
        const initConfig = new InitPrompt()
        await initConfig.run()
      }
    } catch (error) {
      console.error(`\n❌ Error: ${formatError(error)}`)
      process.exit(1)
    }
  })

try {
  program.parse()
} catch (error) {
  console.error(`\n❌ Error: ${formatError(error)}`)
  process.exit(1)
}
